# Generated by Django 5.2.5 on 2025-09-15 11:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Roupa')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço (R$)')),
                ('categoria', models.CharField(choices=[('vestido', 'Vestido'), ('blusa', 'Blusa'), ('calca', 'Calça'), ('saia', 'Saia'), ('conjunto', 'Conjunto'), ('acessorios', 'Acessórios')], max_length=20, verbose_name='Categoria')),
                ('imagem', models.ImageField(upload_to='roupas/', verbose_name='Imagem da Roupa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Roupa',
                'verbose_name_plural': 'Roupas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
