# Generated by Django 5.2.5 on 2025-09-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pag1', '0001_initial'),
    ]

    operations = [
    ]
