# Generated by Django 5.2.5 on 2025-09-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag1', '0002_auto_20250915_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='roupa',
            name='tamanhos',
            field=models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('P,M', 'P, M'), ('M,G', 'M, G'), ('G,GG', 'G, GG'), ('P,M,G', 'P, M, G'), ('M,G,GG', 'M, G, GG'), ('P,M,G,GG', 'P, M, G, GG')], default='P,M,G', max_length=20, verbose_name='Tamanhos Disponíveis'),
        ),
        migrations.RenameField(
            model_name='roupa',
            old_name='imagem',
            new_name='imagem_principal',
        ),
        migrations.AddField(
            model_name='roupa',
            name='imagem_2',
            field=models.ImageField(blank=True, null=True, upload_to='roupas/', verbose_name='Imagem 2'),
        ),
        migrations.AddField(
            model_name='roupa',
            name='imagem_3',
            field=models.ImageField(blank=True, null=True, upload_to='roupas/', verbose_name='Imagem 3'),
        ),
    ]
