# Generated by Django 5.2.5 on 2025-09-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag1', '0003_auto_20250915_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupa',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='roupas/', verbose_name='Imagem Principal'),
        ),
    ]
