# Generated by Django 5.2.5 on 2025-09-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag1', '0004_alter_roupa_imagem_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='roupa',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Desmarque para ocultar este produto do catálogo público', verbose_name='Produto Ativo'),
        ),
    ]
